# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: php:7.4-apache

pipelines:
  default:
    - step:
        name: Setup and Run Tests
        services:
          - mysql
        caches:
          - composer
        script:
          # Install dependencies for Apache and PHP
          - apt-get update && apt-get install -y unzip libpng-dev libjpeg-dev libfreetype6-dev
          - docker-php-ext-configure gd --with-freetype --with-jpeg
          - docker-php-ext-install gd mysqli
          - docker-php-ext-enable mysqli

          # Start Apache
          - echo "<?php phpinfo(); ?>" > /var/www/html/index.php
          - service apache2 restart

          # Run the Test controller
          - php index.php test

