services:
  db:
    image: postgres:15
    container_name: admin-panel-db
    env_file:
      - ./Api/.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: admin-panel-api
    env_file:
      - ./Api/.env
    depends_on:
      - db
    ports:
      - '5209:5209' 
    restart: always

  webapp:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    container_name: admin-panel-webapp
    depends_on:
      - api
    ports:
      - '5173:5173' # porta do Vite
    environment:
      - VITE_API_BASE_URL=http://localhost:5209/api
    restart: always

volumes:
  pgdata:
